name: 'Lint'

on:
  - push
  - pull_request

jobs:
  SwiftFormat:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nicklockwood/swiftformat:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftFormat
        run: swiftformat --lint --reporter github-actions-log .
